export * from './captcha.service';
import { CaptchaService } from './captcha.service';
export * from './events.service';
import { EventsService } from './events.service';
export * from './file.service';
import { FileService } from './file.service';
export * from './games.service';
import { GamesService } from './games.service';
export * from './news.service';
import { NewsService } from './news.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [CaptchaService, EventsService, FileService, GamesService, NewsService, UsersService];
