// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Esport.Backend.Enums;
using System;
using System.Collections.Generic;

namespace Esport.Backend.Entities;

public partial class AuthRole
{
    public int Id { get; set; }

    public UserRole Role { get; set; }

    public virtual ICollection<AuthUser> Users { get; set; } = new List<AuthUser>();
}