// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Esport.Backend.Entities;

public partial class Contact
{
    public int Id { get; set; }

    public string ContactFrom { get; set; }

    public string ContactName { get; set; }

    public string ContactMobile { get; set; }

    public string Subject { get; set; }

    public string Body { get; set; }
}