// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Esport.Backend.Entities;

public partial class EventsUser
{
    public int EventId { get; set; }

    public int UserId { get; set; }

    public DateTime? Invited { get; set; }

    public DateTime? Accepted { get; set; }

    public DateTime? Declined { get; set; }

    public virtual Event Event { get; set; }

    public virtual User User { get; set; }
}