// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Esport.Backend.Entities;

public partial class Event
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public DateTime StartDateTime { get; set; }

    public DateTime EndDateTime { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedDateTime { get; set; }

    public virtual AuthUser CreatedByNavigation { get; set; }

    public virtual ICollection<EventsUser> EventsUsers { get; set; } = new List<EventsUser>();

    public virtual ICollection<Team> Teams { get; set; } = new List<Team>();
}