// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Esport.Backend.Enums;
using System;
using System.Collections.Generic;

namespace Esport.Backend.Entities;

public partial class File
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Filename { get; set; }

    public FileType Type { get; set; }

    public virtual ICollection<AuthUser> AuthUsers { get; set; } = new List<AuthUser>();

    public virtual ICollection<News> News { get; set; } = new List<News>();

    public virtual ICollection<Gallery> Galleries { get; set; } = new List<Gallery>();
}