// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Esport.Backend.Entities;

public partial class File
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Filename { get; set; }

    public int Type { get; set; }
}