// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Esport.Backend.Entities;

public partial class Gallery
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public virtual ICollection<File> Images { get; set; } = new List<File>();
}