// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Esport.Backend.Entities;

public partial class Game
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    [JsonIgnore]
    public virtual ICollection<GameServer> GameServers { get; set; } = new List<GameServer>();
    [JsonIgnore]
    public virtual ICollection<UsersGame> UsersGames { get; set; } = new List<UsersGame>();
}