// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Esport.Backend.Entities;

public partial class GameServer
{
    public int Id { get; set; }

    public string Server { get; set; }

    public int Port { get; set; }

    public int GameId { get; set; }

    public virtual Game Game { get; set; }
}