// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Esport.Backend.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Esport.Backend.Entities
{
    public partial interface IDataContextProcedures
    {
        Task<int> NLogAddEntryAsync(string machineName, DateTime? logged, string level, string message, string logger, string properties, string exception, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
