// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Esport.Backend.Entities;

public partial class News
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string MetaDescription { get; set; }

    public string UrlSlug { get; set; }

    public string Content { get; set; }

    public int? ImageId { get; set; }

    public int? CategoryId { get; set; }

    public int CreatedBy { get; set; }

    public int UpdatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsPublished { get; set; }

    [JsonIgnore]
    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<NewsTag> NewsTags { get; set; } = new List<NewsTag>();

    [JsonIgnore]
    public virtual User UpdatedByNavigation { get; set; }
}