// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Esport.Backend.Entities;

public partial class NewsTag
{
    public int NewsId { get; set; }

    public int TagId { get; set; }

    [JsonIgnore]
    public virtual News News { get; set; }

    [JsonIgnore]
    public virtual Tag Tag { get; set; }
}