// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Esport.Backend.Entities;

public partial class Nlog
{
    public int Id { get; set; }

    public string MachineName { get; set; }

    public DateTime Logged { get; set; }

    public string Level { get; set; }

    public string Message { get; set; }

    public string Logger { get; set; }

    public string Properties { get; set; }

    public string Exception { get; set; }
}