// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Esport.Backend.Entities;

public partial class SchemaVersion
{
    public int Id { get; set; }

    public string ScriptName { get; set; }

    public DateTime Applied { get; set; }
}