// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Esport.Backend.Entities;

public partial class UsersGame
{
    public int GameId { get; set; }

    public int UserId { get; set; }

    public string InGameName { get; set; }

    public virtual Game Game { get; set; }

    public virtual AuthUser User { get; set; }
}