// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Esport.Backend.Entities;

public partial class UsersTeam
{
    public int TeamId { get; set; }

    public int MemberId { get; set; }

    [JsonIgnore]
    public virtual User Member { get; set; }

    [JsonIgnore]
    public virtual Team Team { get; set; }
}