/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRole } from './userRole';


export interface AuthenticateResponse { 
    id: number;
    firstName: string;
    lastName: string;
    username: string;
    role: UserRole;
    token: string;
}
export namespace AuthenticateResponse {
}


