/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthRole } from './authRole';
import { News } from './news';
import { Event } from './event';
import { Team } from './team';
import { EventsUser } from './eventsUser';
import { UsersGame } from './usersGame';


export interface AuthUser { 
    id: number;
    parentId?: number;
    firstName?: string;
    lastName?: string;
    username?: string;
    createdUtc: string;
    addressStreet?: string;
    addressStreetNumber?: number;
    addressFloor?: string;
    addressSide?: string;
    addressPostalCode?: string;
    addressCity?: string;
    mobile?: string;
    consentShowImages: boolean;
    canBringLaptop: boolean;
    canBringStationaryPc: boolean;
    canBringPlaystation: boolean;
    isActivated: boolean;
    imageId?: number;
    events?: Array<Event>;
    eventsUsers?: Array<EventsUser>;
    image?: any;
    inverseParent?: Array<AuthUser>;
    newsCreatedByNavigations?: Array<News>;
    newsUpdatedByNavigations?: Array<News>;
    parent?: AuthUser;
    usersGames?: Array<UsersGame>;
    roles?: Array<AuthRole>;
    teams?: Array<Team>;
}

