/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRole } from './userRole';
import { AuthUser } from './authUser';


export interface AuthRole { 
    id: number;
    role: UserRole;
    users?: Array<AuthUser>;
}
export namespace AuthRole {
}


