/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';


export interface AuthenticateResponse { 
    id: number;
    firstName: string;
    lastName: string;
    username: string;
    roles: Array<Role>;
    token: string;
}

