/**
 * Hourplanner.com API
 *
 * Contact: mail@hourplanner.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthenticateRequest { 
    username: string;
    password: string;
}

