/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CaptchaDto } from './captchaDto';


export interface ContactResponse { 
    ok: boolean;
    message?: string;
    captcha?: CaptchaDto;
}

