/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContactRequest { 
    contactFrom: string;
    contactName: string;
    subject: string;
    body: string;
    captchaId: string;
    captchaCode: string;
    contactMobile?: string;
}

