/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventSubmitRequest { 
    id: number;
    name: string;
    description: string;
    startDateTime: string;
    endDateTime: string;
    eventsUsers: Array<number>;
    teams: Array<number>;
}

