/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Team } from './team';
import { EventsUser } from './eventsUser';


export interface Event { 
    id: number;
    name?: string;
    description?: string;
    startDateTime: string;
    endDateTime: string;
    createdBy: number;
    createdDateTime: string;
    createdByNavigation?: User;
    eventsUsers?: Array<EventsUser>;
    teams?: Array<Team>;
}

