/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Event } from './event';


export interface EventsUser { 
    eventId: number;
    userId: number;
    invited?: string;
    accepted?: string;
    declined?: string;
    event?: Event;
    user?: User;
}

