/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventParticipants { 
    accepted: number;
    declined: number;
    invited: number;
    laptops: number;
    desktops: number;
    playstations: number;
}

