/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HolidayWeekendWorkdayDto } from './holidayWeekendWorkdayDto';
import { Event } from './event';


export interface EventDto { 
    events: Array<Event>;
    weekendWorkday: HolidayWeekendWorkdayDto;
}

