/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export const FileUploadType = {
    None: 'None',
    News: 'News',
    User: 'User',
    Gallery: 'Gallery'
} as const;
export type FileUploadType = typeof FileUploadType[keyof typeof FileUploadType];

