/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export const FileType = {
    None: 'None',
    Image: 'Image'
} as const;
export type FileType = typeof FileType[keyof typeof FileType];

