/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export const FileState = {
    Failed: 'Failed',
    BadRequest: 'BadRequest',
    Success: 'Success'
} as const;
export type FileState = typeof FileState[keyof typeof FileState];

