/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameServer } from './gameServer';
import { UsersGame } from './usersGame';


export interface Game { 
    id: number;
    name?: string;
    description?: string;
    logo?: string;
    gameServers?: Array<GameServer>;
    usersGames?: Array<UsersGame>;
}

