/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Game } from './game';
import { GameServer } from './gameServer';


export interface GameServerDto { 
    game: Game;
    gameServer: GameServer;
}

