/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileType } from './fileType';
import { Gallery } from './gallery';
import { News } from './news';
import { AuthUser } from './authUser';


export interface ModelFile { 
    id: number;
    title?: string;
    filename?: string;
    type: FileType;
    authUsers?: Array<AuthUser>;
    news?: Array<News>;
    galleries?: Array<Gallery>;
}
export namespace ModelFile {
}


