/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { News } from './news';


export interface ModelFile { 
    id: number;
    title?: string;
    filename?: string;
    type: number;
    news?: Array<News>;
}

