/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { NewsTag } from './newsTag';


export interface News { 
    id: number;
    title?: string;
    metaDescription?: string;
    urlSlug?: string;
    content?: string;
    imageId?: number;
    categoryId?: number;
    createdBy: number;
    updatedBy: number;
    createdAt: string;
    updatedAt: string;
    isPublished: boolean;
    createdByNavigation?: User;
    newsTags?: Array<NewsTag>;
    updatedByNavigation?: User;
}

