/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { UserRole } from './userRole';


export interface Role { 
    id: number;
    userRole: UserRole;
    users?: Array<User>;
}
export namespace Role {
}


