/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Event } from './event';
import { AuthUser } from './authUser';


export interface Team { 
    id: number;
    name?: string;
    description?: string;
    validFrom: string;
    validTo?: string;
    events?: Array<Event>;
    members?: Array<AuthUser>;
}

