/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateUserRequest { 
    id: number;
    username: string;
    firstName: string;
    lastName: string;
    addressStreet: string;
    addressStreetNumber: number;
    addressFloor?: string;
    addressSide?: string;
    addressPostalCode: string;
    addressCity: string;
    mobile?: string;
    consentShowImages: boolean;
    canBringLaptop: boolean;
    canBringStationaryPc: boolean;
    canBringPlaystation: boolean;
}

