/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRole } from './userRole';
import { News } from './news';
import { Event } from './event';
import { EventsUser } from './eventsUser';
import { UsersGame } from './usersGame';
import { UsersTeam } from './usersTeam';


export interface User { 
    id: number;
    parentId?: number;
    firstName?: string;
    lastName?: string;
    username?: string;
    role: UserRole;
    createdUtc: string;
    passwordHash?: string;
    passwordResetToken?: string;
    passwordResetTokenExpiration: string;
    addressStreet?: string;
    addressStreetNumber?: number;
    addressFloor?: string;
    addressSide?: string;
    addressPostalCode?: string;
    addressCity?: string;
    mobile?: string;
    consentShowImages: boolean;
    canBringLaptop: boolean;
    canBringStationaryPc: boolean;
    canBringPlaystation: boolean;
    events?: Array<Event>;
    eventsUsers?: Array<EventsUser>;
    inverseParent?: Array<User>;
    newsCreatedByNavigations?: Array<News>;
    newsUpdatedByNavigations?: Array<News>;
    parent?: User;
    usersGames?: Array<UsersGame>;
    usersTeams?: Array<UsersTeam>;
}
export namespace User {
}


