/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export const UserRole = {
    Admin: 'Admin',
    Family: 'Family',
    Friend: 'Friend',
    User: 'User',
    MemberKid: 'MemberKid',
    MemberAdult: 'MemberAdult'
} as const;
export type UserRole = typeof UserRole[keyof typeof UserRole];

