/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export const UserRole = {
    Admin: 'Admin',
    Pending: 'Pending',
    Editor: 'Editor',
    MemberAdult: 'MemberAdult',
    MemberKid: 'MemberKid'
} as const;
export type UserRole = typeof UserRole[keyof typeof UserRole];

