/**
 * esport.p1s.dk API
 *
 * Contact: rvs@easymodules.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Game } from './game';
import { User } from './user';


export interface UsersGame { 
    gameId: number;
    userId: number;
    inGameName?: string;
    game?: Game;
    user?: User;
}

